Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02396cdd13e9a1257 # Use a suitable Amazon Machine Image (AMI) for your region and requirements
      KeyName: ec2-cloudformation-key-pair # Replace with your own key pair name
      SecurityGroupIds: 
        - sg-04596f4a80d2c4550 # Replace with your own security group ID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd.service
          systemctl enable httpd.service